/**
 * TraceGraphTypes — shared type definitions and static lookup tables for the
 * requirements trace-graph experience. Pure module, no scene access, no state.
 */

export type RequirementTypeCode = "UR" | "SR" | "DIR" | "SWR"

export interface Requirement {
  /**
   * Globally unique UUID — the absolute source of truth for this
   * requirement's identity. Assigned once at creation (TraceGraphMockData)
   * and NEVER changed thereafter, even across a type change (see
   * TraceGraphState.setType). This is the sole key used for identity/wiring
   * everywhere: TraceGraphState's Map key, TraceGraphRenderer's node map key
   * and every EdgeHandle's fromId/toId, every other requirement's
   * traceLinks entries, and selection tracking (TraceGraphMain.selectedId /
   * TraceGraphRenderer's own selectedId). Decoupling identity from the
   * renamable `name` display string means a type change (which regenerates
   * `name`, see TraceGraphState.setType) never has to cascade-rename any
   * reference — every Map/array that identifies this requirement keeps using
   * `id` unchanged, so there is nothing to leave dangling. Must NOT be used
   * for display — use `name` instead.
   */
  id: string
  /**
   * Human-readable DISPLAY string (e.g. "SR-02"). Regenerated by
   * TraceGraphState.setType() whenever the requirement's type changes, using
   * the next available zero-padded number for the new type. Safe to read for
   * display anywhere (headers, node labels, trace-link labels) — must NOT be
   * used for identity/lookup/traceability/wiring, use `id` instead.
   */
  name: string
  title: string
  description: string
  type: RequirementTypeCode
  /**
   * IDs (UUIDs) of the requirement(s) THIS one "traces to" — a strict
   * top-down hierarchy (UR -> SR -> {DIR, SWR}, see ALLOWED_TRACE_TARGET_TYPES
   * below), so the array lives on the UPPER-level requirement and references
   * the lower-level one(s) it decomposes into: a UR's traceLinks holds SR
   * ids, an SR's holds DIR/SWR ids, and DIR/SWR always have an empty array
   * (they are the bottom of the hierarchy — nothing to trace to). Rendered
   * as the "Traces to" section in the detail panel; the reverse lookup (who
   * references ME) is computed dynamically at runtime by
   * TraceGraphState.getChildren() — upward traces are never stored,
   * rendered as "Traced by". Entries are immutable UUIDs, not display
   * names, so they survive a rename.
   */
  traceLinks: string[]
}

export interface TypeInfo {
  code: RequirementTypeCode
  label: string
}

export const TYPE_INFO: Record<RequirementTypeCode, TypeInfo> = {
  UR: { code: "UR", label: "User Requirement" },
  SR: { code: "SR", label: "System Requirement" },
  DIR: { code: "DIR", label: "Design Input Requirement" },
  SWR: { code: "SWR", label: "Software Requirement" },
}

/** Top-to-bottom V-model layer order — index 0 is the topmost graph layer. */
export const TYPE_ORDER: RequirementTypeCode[] = ["UR", "SR", "DIR", "SWR"]

/**
 * Strict top-down traceability hierarchy: which type(s) a requirement of a
 * given type is allowed to "trace to" (i.e. allowed to hold in its OWN
 * `traceLinks` array — see the direction note on `Requirement.traceLinks`).
 *
 *   UR  -> SR              (top-level user needs decompose into system reqs)
 *   SR  -> DIR, SWR        (middle layer, decomposes into both leaf types)
 *   DIR -> (none)          (bottom of the hierarchy)
 *   SWR -> (none)          (bottom of the hierarchy)
 *
 * Used by TraceGraphState.addTraceLink() to reject an out-of-hierarchy link
 * before it's created, and by setType()'s post-rename pruning to drop any
 * existing link (in either direction) that the hierarchy no longer permits
 * once a requirement's type has changed.
 */
export const ALLOWED_TRACE_TARGET_TYPES: Record<RequirementTypeCode, RequirementTypeCode[]> = {
  UR: ["SR"],
  SR: ["DIR", "SWR"],
  DIR: [],
  SWR: [],
}

export type RequirementCounts = Record<RequirementTypeCode, number>
